In [1]:
import numpy as np
import math

import torch
import torch.nn as nn
import torchvision
from torch.utils.data import Dataset,DataLoader

In [2]:
DATA_URL = 'https://raw.githubusercontent.com/python-engineer/pytorchTutorial/master/data/wine/wine.csv'

In [3]:
import pandas as pd

data_df = pd.read_csv(DATA_URL)
data_df.head()

Wine  Alcohol  Malic.acid   Ash  ...  Color.int   Hue    OD  Proline
0     1    14.23        1.71  2.43  ...       5.64  1.04  3.92     1065
1     1    13.20        1.78  2.14  ...       4.38  1.05  3.40     1050
2     1    13.16        2.36  2.67  ...       5.68  1.03  3.17     1185
3     1    14.37        1.95  2.50  ...       7.80  0.86  3.45     1480
4     1    13.24        2.59  2.87  ...       4.32  1.04  2.93      735

[5 rows x 14 columns]

In [4]:
# dataframe to numpy

df_npy = data_df.to_numpy(dtype=np.float32)
df_npy,type(df_npy)

(array([[1.000e+00, 1.423e+01, 1.710e+00, ..., 1.040e+00, 3.920e+00,
         1.065e+03],
        [1.000e+00, 1.320e+01, 1.780e+00, ..., 1.050e+00, 3.400e+00,
         1.050e+03],
        [1.000e+00, 1.316e+01, 2.360e+00, ..., 1.030e+00, 3.170e+00,
         1.185e+03],
        ...,
        [3.000e+00, 1.327e+01, 4.280e+00, ..., 5.900e-01, 1.560e+00,
         8.350e+02],
        [3.000e+00, 1.317e+01, 2.590e+00, ..., 6.000e-01, 1.620e+00,
         8.400e+02],
        [3.000e+00, 1.413e+01, 4.100e+00, ..., 6.100e-01, 1.600e+00,
         5.600e+02]], dtype=float32), numpy.ndarray)

In [5]:
df_npy.shape

(178, 14)

### using Dataset and DataLoader classes

In [6]:
# custom Dataset class

class WineDataset(Dataset):

    def __init__(self):
        # Data loading
        self.X = torch.from_numpy(df_npy[:,1:]) # all rows excluding colIndex = 0 
        self.y = torch.from_numpy(df_npy[:,[0]]) # all rows of first column
        self.n_samples = df_npy.shape[0]

    def __getitem__(self,index):
        # returns item at index e.g. dataset[index]
        return self.X[index], self.y[index]

    def __len__(self):
        # returns length of dataset
        return self.n_samples
        

In [7]:
dataset = WineDataset()
first_data = dataset[0]
features,labels = first_data
print(features,labels)

tensor([1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
        3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
        1.0650e+03]) tensor([1.])


In [8]:
dataloader = DataLoader(dataset=dataset,
                        batch_size=4,
                        shuffle=True,
                        num_workers=2)

dataiter = iter(dataloader)
data = dataiter.next()
features,labels = data
print(features,labels)

tensor([[1.3560e+01, 1.7100e+00, 2.3100e+00, 1.6200e+01, 1.1700e+02, 3.1500e+00,
         3.2900e+00, 3.4000e-01, 2.3400e+00, 6.1300e+00, 9.5000e-01, 3.3800e+00,
         7.9500e+02],
        [1.2840e+01, 2.9600e+00, 2.6100e+00, 2.4000e+01, 1.0100e+02, 2.3200e+00,
         6.0000e-01, 5.3000e-01, 8.1000e-01, 4.9200e+00, 8.9000e-01, 2.1500e+00,
         5.9000e+02],
        [1.2250e+01, 3.8800e+00, 2.2000e+00, 1.8500e+01, 1.1200e+02, 1.3800e+00,
         7.8000e-01, 2.9000e-01, 1.1400e+00, 8.2100e+00, 6.5000e-01, 2.0000e+00,
         8.5500e+02],
        [1.3070e+01, 1.5000e+00, 2.1000e+00, 1.5500e+01, 9.8000e+01, 2.4000e+00,
         2.6400e+00, 2.8000e-01, 1.3700e+00, 3.7000e+00, 1.1800e+00, 2.6900e+00,
         1.0200e+03]]) tensor([[1.],
        [3.],
        [3.],
        [1.]])


In [9]:
# training loop - dummy 
num_epochs = 2
total_samples = len(dataset)
n_iters = math.ceil(total_samples/4) # batch_size
print(total_samples,n_iters)

for epoch in range(num_epochs):
    # loop over the dataloader - unpack the batch_index and the tuple
    for i,(inputs,labels) in enumerate(dataloader):
        '''
        1.forward 
        2.backward 
        3.updates
        '''
        if (i+1)%5 == 0:
            print(f'Epoch {epoch+1}/{num_epochs}, step {i+1}/{n_iters}, inputs {inputs.shape}')


178 45
Epoch 1/2, step 5/45, inputs torch.Size([4, 13])
Epoch 1/2, step 10/45, inputs torch.Size([4, 13])
Epoch 1/2, step 15/45, inputs torch.Size([4, 13])
Epoch 1/2, step 20/45, inputs torch.Size([4, 13])
Epoch 1/2, step 25/45, inputs torch.Size([4, 13])
Epoch 1/2, step 30/45, inputs torch.Size([4, 13])
Epoch 1/2, step 35/45, inputs torch.Size([4, 13])
Epoch 1/2, step 40/45, inputs torch.Size([4, 13])
Epoch 1/2, step 45/45, inputs torch.Size([2, 13])
Epoch 2/2, step 5/45, inputs torch.Size([4, 13])
Epoch 2/2, step 10/45, inputs torch.Size([4, 13])
Epoch 2/2, step 15/45, inputs torch.Size([4, 13])
Epoch 2/2, step 20/45, inputs torch.Size([4, 13])
Epoch 2/2, step 25/45, inputs torch.Size([4, 13])
Epoch 2/2, step 30/45, inputs torch.Size([4, 13])
Epoch 2/2, step 35/45, inputs torch.Size([4, 13])
Epoch 2/2, step 40/45, inputs torch.Size([4, 13])
Epoch 2/2, step 45/45, inputs torch.Size([2, 13])


### using transforms 

In [10]:
'''
transforms:

on Images
----------------- 
CenterCrop, Greyscale, Pad, RandomAffine
RandomCrop, RandomHorizonalFlip, RandomRotation
Resize, Scale

on Tensors
-----------------
LinearTransformation,Normalize,RandomErasing

Conversion
-----------------
ToPILImage: from tensor or ndarray
ToTensor: from numpy.ndarray or PILImage

Generic
-----------------
use Lambda

Custom
-----------------
write own class

compose multiple Transforms
------------------------------
composed = transforms.Compose([
                    Rescale(256),
                    RandomCrop(224)
                    ])

# Modify the CustomDataset class to take transform as input in the constructor  

'''


'\ntransforms:\n\non Images\n----------------- \nCenterCrop, Greyscale, Pad, RandomAffine\nRandomCrop, RandomHorizonalFlip, RandomRotation\nResize, Scale\n\non Tensors\n-----------------\nLinearTransformation,Normalize,RandomErasing\n\nConversion\n-----------------\nToPILImage: from tensor or ndarray\nToTensor: from numpy.ndarray or PILImage\n\nGeneric\n-----------------\nuse Lambda\n\nCustom\n-----------------\nwrite own class\n\ncompose multiple Transforms\n------------------------------\ncomposed = transforms.Compose([\n                    Rescale(256),\n                    RandomCrop(224)\n                    ])\n\n# Modify the CustomDataset class to take transform as input in the constructor  \n\n'

In [11]:
class WineDataset(Dataset):

    def __init__(self,transform=None):
        # Data loading - note we don't convert to tensor here
        self.X = df_npy[:,1:]
        self.y = df_npy[:,[0]]
        self.n_samples = df_npy.shape[0]
        self.transform = transform

    def __getitem__(self,index):
        # returns item at index e.g. dataset[index]
        sample = self.X[index], self.y[index]

        if self.transform:
            sample = self.transform(sample)

        return sample

    def __len__(self):
        # returns length of dataset
        return self.n_samples


# custom transform classes

class ToTensor:
    def __call__(self,sample):
        inputs,targets = sample
        return torch.from_numpy(inputs),torch.from_numpy(targets)

class MulTransform:
    def __init__(self,factor):
        self.factor = factor

    def __call__(self,sample):
        inputs,targets = sample
        inputs *= self.factor
        return inputs,targets
                

In [12]:
# multiple transforms: transforms.Compose([...])

composed = torchvision.transforms.Compose([ToTensor(),MulTransform(2)])

dataset = WineDataset(transform=composed)

first_data = dataset[0]
features,labels = first_data
print(type(features),type(labels))

<class 'torch.Tensor'> <class 'torch.Tensor'>


In [13]:
# crossentropy loss

def cross_entropy(actual,predicted):
    loss = -np.sum(actual*np.log(predicted))
    return loss

# actual labels must be one-hot encoded
Y_actual = np.array([1,0,0])

Y_pred_good = np.array([0.7,0.2,0.1])
Y_pred_bad = np.array([0.3,0.3,0.4])

print(cross_entropy(Y_actual,Y_pred_good))
print(cross_entropy(Y_actual,Y_pred_bad))

0.35667494393873245
1.2039728043259361


In [16]:
'''
nn.CrossEntropyLoss()
--------------------------
- no softmax in last layer needed as it itself applies softmax
- Y_actual has class labels and NOT one-hot encodings
- Y_pred has raw scores and NOT softmax outputs

'''

loss = nn.CrossEntropyLoss()

Y_actual = torch.tensor([2,0,1])

# shape = n_samples * n_classes = 3x3
Y_pred_good = torch.tensor([[2.0, 1.0, 3.1],
                            [2.3, 0.1, 0.9],
                            [1.2, 4.6, 1.2]])
Y_pred_bad = torch.tensor([[0.5, 2.0, 0.3],
                           [0.1, 2.3, 4.3],
                           [3.4, 0.9, 3.2]])

l1 = loss(Y_pred_good,Y_actual)
l2 = loss(Y_pred_bad,Y_actual)

print('L1 = '+str(l1.item()))
print('L2 = '+str(l2.item()))

_,predictions1 = torch.max(Y_pred_good,1)
_,predictions2 = torch.max(Y_pred_bad,1)

print(predictions1)
print(predictions2)

L1 = 0.24847181141376495
L2 = 3.17431640625
tensor([2, 0, 1])
tensor([1, 2, 0])


In [ ]:
'''
Binary classification - use sigmoid output and use nn.BCELoss()

Multiclass classification - use nn.CrossEntropyLoss() [it already constitues softmax]

'''

In [17]:
# Multiclass classification - Model class

class Net(nn.Module):
    def __init__(self,input_size,hidden_size):
        super(NeuralNet,self).__init__()
        self.linear1 = nn.Linear(input_size,hidden_size)
        self.relu = nn.ReLU()
        self.linear2 = nn.Linear(hidden_size,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,x):
        x1 = self.linear1(x)
        x1 = self.relu(x1)
        x2 = self.linear2(x1)
        x2 = self.sigmoid(x2)
        return x1,x2

### CNN practical - MNIST (obvious choice for noobs :P )

In [6]:
import os
import math
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

import torch
import torch.nn as nn
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import Dataset,DataLoader

In [3]:
# device config
device = None
if torch.cuda.is_available():
    device = torch.device('cuda')
else:
    device = torch.device('cpu')

device

device(type='cuda')

In [4]:
# hyperparameters
input_size = 784 # 28x28
hidden_size = 100
num_classes = 10
num_epochs = 50
batch_size = 100
learning_rate = 0.01

In [5]:
# MNIST
train_dataset = torchvision.datasets.MNIST(root='./data',train=True,
                                           transform=transforms.ToTensor(),
                                           download=True)

test_dataset = torchvision.datasets.MNIST(root='./data',train=False,
                                          transform=transforms.ToTensor())

Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw


Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw
Processing...
Done!


/usr/local/lib/python3.7/dist-packages/torchvision/datasets/mnist.py:480: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /pytorch/torch/csrc/utils/tensor_numpy.cpp:141.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [7]:
# DataLoader
train_loader = DataLoader(dataset=train_dataset,
                          batch_size=batch_size,
                          shuffle=True)

test_loader = DataLoader(dataset=test_dataset,
                         batch_size=batch_size,
                         shuffle=False)

examples = iter(train_loader)
samples,labels = examples.next()
print(samples.shape,labels.shape) 
# 100 is for batch_size, 1 is for color channel, 28x28 is dimension of image

torch.Size([100, 1, 28, 28]) torch.Size([100])


In [18]:
# model class
class NeuralNet(nn.Module):
    def __init__(self,input_size,hidden_size,num_classes):
        super(NeuralNet,self).__init__()
        self.linear1 = nn.Linear(input_size,hidden_size)
        self.relu = nn.ReLU()
        self.linear2 =  nn.Linear(hidden_size,num_classes)

    def forward(self,x):
        x1 = self.linear1(x)
        x1 = self.relu(x1)
        x2 = self.linear2(x1)
        return x2 # no softmax as nn.CrossEntropyLoss() will put it 

In [19]:
# defining model
model = NeuralNet(input_size,hidden_size,num_classes)
model=model.to(device)

# loss and optimizer
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(),lr=learning_rate)

In [20]:
# training loop
n_total_steps = len(train_loader) # total nos of training samples
for epoch in range(num_epochs):
    for ii,(images,labels) in enumerate(train_loader):
        # reshape images - need to convert (100,1,28,28) to (100,28*28)
        images = images.reshape(-1,28*28).to(device)
        labels = labels.to(device) # pushing tensor to gpu if present

        # forward 
        outputs = model(images)
        loss = criterion(outputs,labels)

        # backward
        loss.backward()

        # update
        optimizer.step()
        optimizer.zero_grad()

        if (ii+1)%100 == 0:
            print(f'epoch {epoch+1}/{num_epochs}, step {ii+1}/{n_total_steps},loss = {loss.item()}')



epoch 1/50, step 100/600,loss = 0.3077969551086426
epoch 1/50, step 200/600,loss = 0.1612159162759781
epoch 1/50, step 300/600,loss = 0.1899344027042389
epoch 1/50, step 400/600,loss = 0.07646738737821579
epoch 1/50, step 500/600,loss = 0.08276554942131042
epoch 1/50, step 600/600,loss = 0.08208953589200974
epoch 2/50, step 100/600,loss = 0.09048011153936386
epoch 2/50, step 200/600,loss = 0.051778536289930344
epoch 2/50, step 300/600,loss = 0.06051763519644737
epoch 2/50, step 400/600,loss = 0.18942807614803314
epoch 2/50, step 500/600,loss = 0.12039586156606674
epoch 2/50, step 600/600,loss = 0.21245518326759338
epoch 3/50, step 100/600,loss = 0.07504168152809143
epoch 3/50, step 200/600,loss = 0.13803039491176605
epoch 3/50, step 300/600,loss = 0.049999576061964035
epoch 3/50, step 400/600,loss = 0.031740155071020126
epoch 3/50, step 500/600,loss = 0.06308349221944809
epoch 3/50, step 600/600,loss = 0.178181454539299
epoch 4/50, step 100/600,loss = 0.04735518991947174
epoch 4/50, st

In [21]:
# testing loop
with torch.no_grad():
    n_correct = 0
    n_samples = 0
    for images,labels in test_loader:
        images = images.reshape(-1,28*28).to(device)
        labels = labels.to(device)
        
        outputs = model(images)

        # value,index
        _, preds = torch.max(outputs,1)
        n_samples += labels.shape[0]
        n_correct += (preds == labels).sum().item()

    accuracy = n_correct/float(n_samples)
    print(f'Accuracy on test data = {accuracy:.4f}')

Accuracy on test data = 0.9708
